In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

print(a)

[-1.52414271  0.18594174 -0.57792236 -1.03947788  0.73520603]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.52414271  0.18594174 -0.57792236 -1.03947788  0.73520603]


Notice how both looks the same (a and a transpose)

* What if we multiplied `a` with `a transpose`?

In [5]:
print(np.dot(a, a.T))

4.31262174919


**Points worth noting**
* Avoid data structures like (5,)
* To use this as a data structure, define shape using (5,1)

In [6]:
a = np.random.randn(5,1)

print(a)

[[-2.19057258]
 [ 0.80385667]
 [ 0.87179308]
 [ 1.04749573]
 [-1.53649412]]


We got a single column array

This is more acceptable and suitable.

In [7]:
print(a.T)

[[-2.19057258  0.80385667  0.87179308  1.04749573 -1.53649412]]


Notice the fucking difference bro

In [8]:
print(np.dot(a, a.T))

[[ 4.79860823 -1.76090637 -1.90972602 -2.29461543  3.36580189]
 [-1.76090637  0.64618554  0.70079668  0.84203643 -1.23512104]
 [-1.90972602  0.70079668  0.76002318  0.91319953 -1.33950494]
 [-2.29461543  0.84203643  0.91319953  1.09724731 -1.60947103]
 [ 3.36580189 -1.23512104 -1.33950494 -1.60947103  2.36081418]]


**VOILA**